# Generated by Django 4.2.8 on 2024-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='gallery')),
                ('material', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('colour', models.CharField(max_length=250)),
            ],
        ),
    ]
